version: '3'
services: 
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: unless-stopped
    environment: 
      - 'ROCKET_TLS={certs="/ssl/bitwarden.crt",key="/ssl/bitwarden.key"}'
    ports: 
      - 8080:80
    volumes: 
      - /media/Storage/bw-data:/data
      - /etc/ssl/certs:/ssl

