version: '3'
services:
  pihole:
    image: pihole/pihole:v5.8.1
    container_name: pihole
    restart: unless-stopped
    environment: 
      - TZ="America/New_York"
    ports: 
      - 53:53/tcp
      - 53:53/udp
      - 8081:80
      - 8443:443
    volumes: 
      - /media/Storage/pi-hole-data/etc-pihole/:/etc/pihole/
      - /media/Storage/pi-hole-data/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns: 
      - 127.0.0.1
      - 1.1.1.1
