version: '3'
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    environment: 
      - TZ="America/New_York"
    ports: 
      - 53:53/tcp
      - 53:53/udp
      - 8081:80
      - 8443:443
    volumes: 
      - /pi-hole-data/etc-pihole/:/etc/pihole/
      - /pi-hole-data/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns: 
      - 127.0.0.1
      - 1.1.1.1