version: '3'
services: 
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: unless-stopped
    environment: 
      - VERSION=latest
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes: 
      - /media/Storage/plex/config:/config
      - /media/Storage/Video/Exercise:/data/video/exercise
      - /media/Storage/Video/KidsMovies:/data/video/kidsmovies
      - /media/Storage/Video/Movies:/data/video/movies
      - /media/Storage/Video/TV:/data/video/tv
      - /media/Storage/Video/YouTube:/data/video/youtube
      - /media/Storage/Zach/Music:/data/audio/music
      - /media/Storage/Zach/Podcasts:/data/audio/podcasts
    network_mode: host