version: '3'
services: 
  emby:
    image: emby/embyserver_arm32v7:4.8.0.21
    container_name: emby
    restart: unless-stopped
    volumes: 
      - /media/Storage/emby/config:/config
      - /media/Storage/Video/Exercise:/data/video/exercise
      - /media/Storage/Video/KidsMovies:/data/video/kidsmovies
      - /media/Storage/Video/Movies:/data/video/movies
      - /media/Storage/Video/TV:/data/video/tv
      - /media/Storage/Video/YouTube:/data/video/youtube
      - /media/Storage/Music:/data/audio/music
      - /media/Storage/Podcasts:/data/audio/podcasts
    ports: 
      - 8096:8096
      - 8920:8920
      - 1900:1900/udp
    environment:
      - UID=$USER_ID
      - GID=$GROUP_ID
  emby-video-converter:
    image: zmad5306/video-converter:1.0.3
    container_name: video-converter
    restart: unless-stopped
    volumes:
      - /media/Storage/Video/YouTube/Movies/NewPipe:/vids