version: '3'
services: 
  emby:
    image: emby/embyserver:4.9.0.4
    container_name: emby
    restart: unless-stopped
    volumes: 
      - /media/Storage/emby/config:/config
      - /media/Storage/Video/Exercise:/data/video/exercise
      - /media/Storage/Video/KidsMovies:/data/video/kidsmovies
      - /media/Storage/Video/Movies:/data/video/movies
      - /media/Storage/Video/TV:/data/video/tv
      - /media/Storage/Video/YouTube:/data/video/youtube
      - /media/Storage/Music:/data/audio/music
      - /media/Storage/Podcasts:/data/audio/podcasts
      - /etc/ssl/certs:/certs
    environment:
      - UID=$USER_ID
      - GID=$GROUP_ID
    ports:
      - 8096:8096
  emby-video-converter:
    image: zmad5306/video-converter:1.0.3
    container_name: emby-video-converter
    restart: unless-stopped
    volumes:
      - /media/Storage/Video/YouTube/Movies/NewPipe:/vids
  emby-proxy:
    image: nginx:1.21.1
    container_name: emby-proxy
    restart: unless-stopped
    volumes:
      - /media/Storage/emby/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs:/ssl
    ports:
      - 8097:443
    depends_on:
      - emby
