version: '3'
services: 
  postgres: 
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - /media/Storage/nextcloud/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    volumes: 
      - /media/Storage/nextcloud/data:/data
      - /media/Storage/nextcloud/html:/var/www/html
    ports: 
      - 8082:80
    depends_on: 
      - postgres
      - protonmail-bridge
  protonmail-bridge: 
    image: shenxn/protonmail-bridge:1.4.5-build
    container_name: protonmail-bridge
    restart: unless-stopped
    volumes:
      - /media/Storage/protonmail:/root
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    volumes: 
      - /media/Storage/nextcloud/nginx/nginx.conf:/etc/nginx/sites-available/default:ro
      - /etc/ssl/certs:/ssl
    ports: 
      - 9999:443
      - 9998:80
    depends_on: 
      - nextcloud
