version: '3'
services: 
  postgres: 
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - /media/Storage/nextcloud/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    volumes: 
      - /media/Storage/nextcloud/data:/data
      - /media/Storage/nextcloud/html:/var/www/html
    ports: 
      - 8082:80
    depends_on: 
      - postgres
  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    environment:
      - username="admin"
      - password=$COLLABORA_PASSWORD
    ports: 
      - 9980:9980
