version: '3'
services: 
  postgres: 
    image: postgres:14.1
    container_name: postgres
    restart: unless-stopped
    volumes:
      - /media/Storage/nextcloud/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  nextcloud:
    image: nextcloud:23.0.0
    container_name: nextcloud
    restart: unless-stopped
    volumes: 
      - /media/Storage/nextcloud/data:/data
      - /media/Storage/nextcloud/html:/var/www/html
    depends_on: 
      - postgres
      - protonmail-bridge
  protonmail-bridge: 
    image: shenxn/protonmail-bridge:1.8.12-build
    container_name: protonmail-bridge
    restart: unless-stopped
    volumes:
      - /media/Storage/protonmail:/root
  nginx-proxy:
    image: nginx:1.21.4
    container_name: nginx-proxy
    restart: unless-stopped
    volumes: 
      - /media/Storage/nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs:/ssl
    ports: 
      - 8082:443
    depends_on: 
      - nextcloud
