version: '3'
services: 
  postgres: 
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - /media/Storage/nextcloud/db:/var/lib/postgresql/data
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    volumes: 
      - /media/Storage/nextcloud/data:/data
      - /media/Storage/nextcloud/html:/var/www/html
    ports: 
      - 8082:80
    depends_on: 
      - postgres
    environment: 
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD