version: '3'
services: 
  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    environment:
      - username="admin"
      - password=$COLLABORA_PASSWORD
    ports: 
      - 9980:9980