version: '3'
services: 
  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    environment:
      - username=admin
      - password=$COLLABORA_PASSWORD
      - domain=192.168.254.249
    ports: 
      - 127.0.0.1:9980:9980