version: '3'
services: 
  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    environment:
      - username="admin"
      - password=$COLLABORA_PASSWORD
      - domain="collabora.local"
    ports: 
      - 127.0.0.1:9980:9980