version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: bridge
volumes:
  portainer_data:
    external: true
    name: portainer_data
