version: '3'
services:
  portainer:
    image: portainer/portainer-ce:2.17.0
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /media/Storage/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
